### ISSUE TITLE
テストにMockを導入する

### ISSUE THREAD

**Issue by yusei53** [KiizanKiizan/Manene#101]
前提として、Mockが必要かどうかを検討し、本issueに取り組む

https://playwright.dev/docs/mock

現状: E2EテストでMockを使う際、axiosを使った場合、Mockが機能せず、リクエストが送られてしまう

解決の選択肢:
- fetchAPIを使い、機能する（解決済）
- このままaxiosを使って、解決する（できていない）
- ID自体をとってくる

**Comment by kotaesaki** [comment]
https://playwright.dev/docs/mock
> Web APIs are usually implemented as HTTP endpoints. Playwright provides APIs to mock and modify network traffic, both HTTP and HTTPS. Any requests that a page does, including [XHRs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) and [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) requests, can be tracked, modified and mocked. With Playwright you can also mock using HAR files that contain multiple network requests made by the page.
