### ISSUE TITLE
アイテム読み取り画面のテスト実装

### ISSUE THREAD

**Issue by kotaesaki** [KiizanKiizan/Manene#117]

**Comment by OHTA1127** [comment]
- [ ] item_detailページに遷移したらバーコードリーダーが表示される
- [ ] アイテムIDを入力していない時にOKを押せない
- [ ] アイテムIDを入力した時にOKを押せる
- [ ] ダイアログのキャンセルを押した時にダイアログが閉じる
- [ ] バーコードを読み込んだ時に、item_detail/[:id]に遷移する

- [ ] トップスを表示できる
- [ ] ボトムスを表示できる
- [ ] アウターを表示できる
- [ ] サブカラーがない時に”なし”と表示される
- [ ] 棚がない時に”なし”と表示される
- [ ] 婚活フラグがfaulseの時に”なし”と表示される
- [ ] ゴム紐フラグがfaulseの時に”なし”と表示される
- [ ] 登録日が存在しない時に""が表示される
