### ISSUE TITLE
返却検品前登録　設計

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#191]

**Comment by ryuhei202** [comment]
# 概要

検品グループに対してカルテを追加する機能。

カルテ内のアイテムを一つでも読み取るとカルテアイテムが全て取得でき、そのカルテは登録中の検品グループに所属することになる。

ユーザーの入れ忘れや、即時検品をすることができる。


# 動画

https://github.com/KiizanKiizan/Manene/assets/105505578/4d564f28-a8d8-46c8-b44b-e92121fe4b98



# 要件

* 現在登録されている検品グループが取得でき、表示できる。

* 現在登録されている検品グループがない場合「グループなし」と表示される。

* レンタル中のアイテムをスキャンしたら、カルテ情報とそのカルテ内に含まれるアイテムが全て表示される。

* レンタル中のアイテムでない場合はエラーメッセージが表示できる。

* 検品グループがないのにアイテムスキャンするとエラーメッセージが表示できる。

* 即時検品をすることができる

* アイテムの入れ忘れを登録することができる。

# Page
## BeforeInspectionsPage(SC)

`GET /igoue_admin/app_api/inspection/before_inspections/accepting_group`で検品グループを取得しBeforeInspectionsContainerに渡す。


# Components
## BeforeInspectionsContainer
<img width="268" alt="スクリーンショット 2023-09-01 14 39 37" src="https://github.com/KiizanKiizan/Manene/assets/105505578/c711bf44-a1b8-4f1a-9419-8a7da360f1f4">

* Header

* Snackbar

* ChartCard

* BeforeInspectionsList

* ScanButton

を配置。その他ロジックを記述


## BeforeInspectionsList
<img width="258" alt="スクリーンショット 2023-09-01 14 39 15" src="https://github.com/KiizanKiizan/Manene/assets/105505578/a39a4ff3-949f-43eb-84f9-f0adbdc8229f">

BeforeInspectionsListItemをmap処理。

## BeforeInspectionsListItem
<img width="310" alt="スクリーンショット 2023-09-01 14 37 12" src="https://github.com/KiizanKiizan/Manene/assets/105505578/5d5dc27d-a443-4104-9c52-6837a939d4b2">



## ChartCard
<img width="298" alt="スクリーンショット 2023-09-01 14 37 57" src="https://github.com/KiizanKiizan/Manene/assets/105505578/3f305f5f-ecbf-4a7d-a14a-728992bf9542">


# API

## GET /igoue_admin/app_api/inspection/before_inspections/accepting_group

> before_inspections#accepting_group

> 現在openしている検品グループを取得するapi

params

無し

response

```ts
TInspectionGroupResponse = {
  inspectionGroups: {
  id: number;
  groupNo: number;
  registrationStartTime: string;
  registrationEndTime: string | null;
  inspectionEndTime: string | null;
  chartCount: number;
  washingItemCount: number;
  purchaseItemCount: number;
 } | null
};

```

## POST /igoue_admin/app_api/inspection/before_inspections

> before_inspections#create

> 読み取ったアイテムを持つカルテを検品グループに登録するためのapi

params

```ts
itemId: number;
```

response

```ts
{
  tChart: {
    id: number;
    tMemberId: number;
    name: string;
    deliveryDate: string;
    tChartItems: {
      id: number;
      itemInfo: {
        id: number;
        size: string;
        itemImageUrl: string;
        mCateSmallName: string;
        mColorName: string;
        mBrandName: string;
      }
    }[]
    purchasedFlag: boolean;
    inspectionStatus: number;
   }
  };
  isCreatedInspectionData: boolean;
  registeredInspectionGroup: {
    id: number;
    groupNo: number;
    registrationStartTime: string;
    registrationEndTime: string | null;
    inspectionEndTime: string | null;
    chartCount: number;
    washingItemCount: number;
    purchaseItemCount: number;
   };
  acceptingInspectionGroup: {
    id: number;
    groupNo: number;
    registrationStartTime: string;
    registrationEndTime: string | null;
    inspectionEndTime: string | null;
    chartCount: number;
    washingItemCount: number;
    purchaseItemCount: number;
   } | null;
  isChartInspected: boolean;
}
```

## PATCH /igoue_admin/app_api/inspection/before_inspections/to_misplaced_item

> before_inspections#to_misplaced_item

> ユーザーが返却し忘れたアイテムを登録するためのapi

params
```ts
chartItemId: number;
```

response

```ts
{
  id: number;
  tMemberId: number;
  name: string;
  deliveryDate: string;
  tChartItems: {
    id: number;
    itemInfo: {
      id: number;
      size: string;
      itemImageUrl: string;
      mCateSmallName: string;
      mColorName: string;
      mBrandName: string;
    }
  }[]
    purchasedFlag: boolean;
    inspectionStatus: number;
 }
}
```

## POST /igoue_admin/app_api/inspection/before_inspections/inspect

> before_inspections#inspect

> 即時検品をした際のapi

params

```ts
chartId: number;
```

response

```ts
{
  tChart: {
    id: number;
    tMemberId: number;
    name: string;
    deliveryDate: string;
    tChartItems: {
      id: number;
      itemInfo: {
        id: number;
        size: string;
        itemImageUrl: string;
        mCateSmallName: string;
        mColorName: string;
        mBrandName: string;
      }
    }[]
    purchasedFlag: boolean;
    inspectionStatus: number;
   }
  };
  isCreatedInspectionData: boolean;
  registeredInspectionGroup: {
    id: number;
    groupNo: number;
    registrationStartTime: string;
    registrationEndTime: string | null;
    inspectionEndTime: string | null;
    chartCount: number;
    washingItemCount: number;
    purchaseItemCount: number;
   };
  acceptingInspectionGroup: {
    id: number;
    groupNo: number;
    registrationStartTime: string;
    registrationEndTime: string | null;
    inspectionEndTime: string | null;
    chartCount: number;
    washingItemCount: number;
    purchaseItemCount: number;
   } | null;
  isChartInspected: boolean;
}
```

**Comment by kotaesaki** [comment]
@ryuhei202 

要件の
> 現在登録されている検品グループが取得でき、表示できる。
現在登録されている検品グループがない場合「グループなし」と表示される。

は「返却検品管理」すでに実装済みだと思うので、このタスク内ではない？

Q: 
一斉検品はもうすでに実装されているんでしたっけ？👀
知らないので教えてほしいんですが、検品グループが複数ある場合ってどのグループに振り分けられるんですか？👀


JSONなどのインデントや読みやすさ意識してもらえたおかげでドキュメント読みやすくなりました！
ありがとうございます！

**Comment by ryuhei202** [comment]
@kotaesaki 

> 現在登録されている検品グループが取得でき、表示できる。
> 現在登録されている検品グループがない場合「グループなし」と表示される。
　
これは返却検品前登録に入った瞬間に、Headerの右上に表示させるやつです！

GET /igoue_admin/app_api/inspection/before_inspections/accepting_groupによってどのグループにアイテムを登録するかという情報を取得しています！

> Q:
> 一斉検品はもうすでに実装されているんでしたっけ？👀
> 知らないので教えてほしいんですが、検品グループが複数ある場合ってどのグループに振り分けられるんですか？👀

A: 

一斉検品はすでに実装済みです！

登録中の検品グループは一つしかないので複数登録できません！

新しく検品グループを作成すると自動で登録中の検品グループが締め切られます！

https://github.com/KiizanKiizan/Manene/pull/178

こちらの動画がわかりやすいかと！
