### ISSUE TITLE
アイテム計測のロジックを整理する

### ISSUE THREAD

**Issue by ytsumori** [KiizanKiizan/Manene#260]
アプリでの画面遷移とデータフローを順番に整理していく

**Comment by ytsumori** [comment]
まずはバーコードリーダを表示して、アイテムのIDをスキャン

スキャンしたら`GET /size_measurement`に`item_id`をbodyに追加してリクエスト送信
レスポンスにはアイテムのサイズ情報とともに

- `need_adjustment_for_length_arm`: 袖の計測値に修正が必要か？
- `need_parts_for_size_calc`: 自動計算される部位が必要か？（婚活アイテムかゴム紐パンツのウエスト）
- `is_size_stable`: サイズが変わらないか？（OEMのアイテムは一定回数クリーニングされた後は計測しなくていいとしている）

の情報が返ってくる

**Comment by ytsumori** [comment]
サイズ計測画面へ遷移

## サイズ確定済みアイテム

サイズ計測が不要の場合（`is_size_stable`が`true`の場合）、サイズ確定済みダイアログに「サイズ計測を開始しますか？」という質問が出るので

- 「はい」を選ぶ：サイズ計測に進む
- 「いいえ」を選ぶ：バーコードリーダー画面に戻る

## 部位サイズ入力

もし`need_parts_for_size_calc`が存在してる場合、全ての値が揃ったら`need_parts_for_size_calc`の部位の数値更新時に`GET /size_calc`にリクエストを送信し、最新のサイズ(S / M / L / XL)を取得して表示を更新する

## 部位ごとの補正

- 袖：Sは-20、Mは-21、Lは-22、XLは-23
- ウエスト：２倍だが、ゴミ紐の場合別ロジック
- 股下：`x - 25 < 0 ? x : 2x - 25`
- 最小ウエスト、最大ウエスト、ヒップ、もも、ふくらはぎ：２倍に

補正後の値と元々の値の差が1以下の場合は更新しない

## フッター確定ボタン

スキップボタンは既にサイズが入力されてる場合に押せる
確定ボタンは全ての部位サイズに値が入力されてる場合に押せる

**Comment by kotaesaki** [comment]
@ytsumori @ryuhei202 
住山さんから口頭で聞いたメモ: 
ビジネスフラグの首のロジックがややこしいので無くしちゃって大丈夫らしい！

**Comment by ytsumori** [comment]
## ウエストの計算ロジック
https://docs.google.com/document/d/1eEm3J-RQ8K7sWbg4q_Arvk_4ukAs3aI3_HiuJXYguBU/edit
https://docs.google.com/document/d/171D7klOIyTMbfsSBXNiVrT3n5bGdGbdvHi7MxQb4rMQ/edit

**Comment by ryuhei202** [comment]
@ytsumori `need_adjustment_for_length_arm`は裄丈統一に伴って不必要になりそう(?)

**Comment by ytsumori** [comment]
@ryuhei202 
ですね！

**Comment by ytsumori** [comment]
一旦既存の仕様はまとめれたのでクローズ
