### ISSUE TITLE
設計

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#264]

**Comment by ryuhei202** [comment]
# 要件

# API

## getSizeMeasurementIndex
> GET /igoue_admin/app_api/size_measurement
> size_mesurement#index
> バーコードで読み取ったアイテムのサイズ情報を取得するためのapi。SC data fetch

params

```ts
itemId: number
```

response

```ts
itemId: number;
input: {
  mCateSmallId: number;
  isMarriage: boolean;
  size: string;
  measurements: {
    part: number;
    value: number
    }[]
  needPartsForSizeCalc: number[];
  isSizeStable: boolean;
  rank: string;
  }
```

**Comment by ytsumori** [comment]
@ryuhei202 
`useSizeMeasurementUpdate`の部位が以前の仕様のままになってるんで更新お願いします！

`useSizeCalcIndex`の部分も更新必要そうですね！（首とか婚活フラグとかは無くすので！

#260

**Comment by ryuhei202** [comment]
@ytsumori 修正しました！確認お願いします！

**Comment by ytsumori** [comment]
@ryuhei202 
あざます！以下気になりました！

`useSizeMeasurementUpdate `
* `shoulder`必要なさそう
* `totalLength`ボトムスの長さってわかるように`bottomsLength`とかが良さそう（着丈の`lengthTop`とかに合わせても良さそう）


`useSizeCalcIndex`
* ウエストだけで良さそう

**Comment by ryuhei202** [comment]
@ytsumori 修正しました！

**Comment by ytsumori** [comment]
@ryuhei202 う〜ん...どっちでもいい気がするなぁw
逆にどっちの方が良さそうすかね？
（切り捨ては小数点以下がある想定での使用なので、整数のみ受け付けて失くすでいいと思ってました！）

**Comment by ryuhei202** [comment]
@ytsumori これくらいのロジックならフロントでやるのがいいと思いました！その方針でいきます！
