### ISSUE TITLE
トップレベルのlayout.tsxにヘッダーを移行

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#53]

**Comment by ryuhei202** [comment]
appbarを消去してheaderをlayout.tsxに移行

**Comment by kojikojiXX** [comment]
@ryuhei202 
江崎さんに相談したところ
useContextを使って、各ページごとでタイトルの部分だけ変更かける処理を追加すれば、app/layout.tsxを動的にすることができることが判明しました！
