### ISSUE TITLE
社内からのみアプリケーションにアクセスできるよう設定する

### ISSUE THREAD

**Issue by ytsumori** [KiizanKiizan/Manene#6]
## 目的
セキュリティの観点で社内で使うアプリなので、社外からアクセスが行えないようにする

## 方法
パッと思いつくのは
* IPアドレスで制限をかける
* Googleアカウントでのログインを必須にする（共有の端末なので、結構面倒？）
など

**Comment by ytsumori** [comment]
@ryuhei202 
結構簡単そうです！

> vercelでホスティングされているnext.jsアプリケーションにIPアドレスでアクセス制限をかける方法は？

GitHub Copilot: VercelでホスティングされているNext.jsアプリケーションにIPアドレスでアクセス制限をかけるには、以下の手順を実行する必要があります。

1. Vercelのダッシュボードにログインし、アプリケーションを選択します。

2. 「Settings」タブをクリックし、「Environment Variables」セクションを見つけます。

3. 「Add」ボタンをクリックして、新しい環境変数を追加します。環境変数の名前を「ALLOWED_IPS」とし、許可するIPアドレスをカンマ区切りで入力します。

4. Next.jsアプリケーションのルートディレクトリに`vercel.json`ファイルを作成します。

5. `vercel.json`ファイルに、以下の内容を追加します。

   ```json
   {
     "version": 2,
     "routes": [
       {
         "src": "/(.*)",
         "headers": {
           "Access-Control-Allow-Origin": "*",
           "Access-Control-Allow-Methods": "GET,HEAD,PUT,PATCH,POST,DELETE",
           "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"
         },
         "handle": "next"
       }
     ],
     "env": {
       "ALLOWED_IPS": "$ALLOWED_IPS"
     }
   }
   ```

   これにより、`ALLOWED_IPS`環境変数が`vercel.json`ファイルに追加されます。

6. `vercel.json`ファイルを保存します。

7. Vercelにデプロイします。

8. アプリケーションにアクセスするには、許可されたIPアドレスからのみアクセスできます。

以上の手順で、VercelでホスティングされているNext.jsアプリケーションにIPアドレスでアクセス制限をかけることができます。

**Comment by ryuhei202** [comment]
@ytsumori ありがとうございます！rails側で弾くイメージでしたが、フロントでそもそも入れない状態にすれば大丈夫そうですね！

**Comment by ryuhei202** [comment]
google認証にするか？

**Comment by ytsumori** [comment]
#44 こちらで引き続き対応
