### ISSUE TITLE
アイテムピック実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#68]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/104
- [ ] https://github.com/KiizanKiizan/Manene/issues/87
```

**Comment by kojikojiXX** [comment]
![image](https://github.com/KiizanKiizan/Manene/assets/63447137/ae8b1c79-808a-40d2-bce7-386998de6ec4)

### ディレクトリ構成
```
app
   L coorde-pick
        L [chartId]
            L page.tsx
   L common
        L barcode
            L barcodeReader.tsx
            L BarcodeInputDialog.tsx
   L coorde-pick
        L CoordePickList.tsx
```

**Comment by kotaesaki** [comment]
@kojikojiXX 
hooksの命名的にはuseItemPick よりもuseCoordePicksPick.tsの方が適切ですかね！

https://github.com/KiizanKiizan/Manene/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB#api%E9%96%A2%E9%80%A3%E3%81%AE%E3%83%95%E3%83%83%E3%82%AF%E3%82%B9%E9%9D%9E%E5%90%8C%E6%9C%9F%E9%96%A2%E6%95%B0

> const {updatedTChartItems, setUpdatedTChartItems} = useState<[]>();
q: これは何に使うイメージでしょうか？👀


あとコード書くときこんな感じで拡張子描くとスタイル的にみやすくなるのでありがたいです！できたらインデントも揃えてもらえると持っと読みやすいです！

<img width="180" alt="スクリーンショット 2023-08-07 18 00 55" src="https://github.com/KiizanKiizan/Manene/assets/65902454/ada97c4d-c8b3-4060-908a-de147e65f7c8">

```ts
export const hoge = () => {
  return <></>
}
```
