### ISSUE TITLE
[アイテム詳細表示]itemDetailCardの作成

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#96]

**Comment by ytsumori** [comment]
@ryuhei202 @kotaesaki @OHTA1127 
responseから表示用のデータへの整形が結構複雑なので、containerとpresentationalコンポーネントに分けて実装進めていこうと思います！

**ItemDetailCardContainer**
responseデータを表示可能の形式に整形

props
```
itemInfo: 
```

**ItemDetailCard**
UIの表示

props
```
itemImageUrl: string
size: string
sizeData: { partName: string, partSize: string }
itemInfo: { label: string, value: string } // 最下部に表示する一覧の情報 
```
